### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by mbloos** [derwish-pro/singlehub#2]
When trying to build I get the following error : 

ERROR in build.js from UglifyJs
Unexpected token: name (Container) [./src/public/nodes/container.ts:34,0][build.js:748,6]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! singlehub@0.0.0 build:webpack: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the singlehub@0.0.0 build:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-11-09T11_43_34_517Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! singlehub@0.0.0 build: `npm run build:ts & npm run build:webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the singlehub@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-11-09T11_43_34_603Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! singlehub@0.0.0 postinstall: `bower install --allow-root & npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the singlehub@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-11-09T11_43_34_960Z-debug.log

**Comment by derwish-pro** [comment]
Please, clone now, and try again

**Comment by mbloos** [comment]
Same Error, except the line numbers changed

 $ node -v
v8.9.1
Running it on a RPi3

If you need more info, let me know


ERROR in build.js from UglifyJs
Unexpected token: name (Container) [./src/nodes/container.ts:33,0][build.js:5268,6]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! singlehub@0.0.0 build:webpack: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the singlehub@0.0.0 build:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-11-10T21_57_39_584Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! singlehub@0.0.0 build: `npm run build:ts & npm run build:webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the singlehub@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-11-10T21_57_39_648Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! singlehub@0.0.0 postinstall: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the singlehub@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-11-10T21_57_39_973Z-debug.log

**Comment by derwish-pro** [comment]
Ok, thank you. I will check it on RPi later.

**Comment by mbloos** [comment]
Let me know if I need to provide more info, I like your design, might be also worth to incorporate mqtt or even talk to the people who design/program ioBroker. I think it might be a good way to incorporate your ideas with a broad array of adapters :-)

**Comment by derwish-pro** [comment]
This bug is fixed

**Comment by derwish-pro** [comment]
You can try to clone it again. Thank you for info.

**Comment by mbloos** [comment]
Yes, it compiles and starts :)
