### ISSUE TITLE
Getting error  Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by bkrajendra** [derwish-pro/singlehub#3]
Just cloned repo and trying to run but getting error
```
 Error: No default engine was specified and no extension was provided.
```
[2017-12-30T07_03_09_242Z-debug.log](https://github.com/derwish-pro/singlehub/files/1594217/2017-12-30T07_03_09_242Z-debug.log)

Initially it run properly when everything i kept as it is.
But latter when i changed "firstRun": true in config file it started giving this error after connection from 
browser.

I'm running on windows 10 64 bit with 
latest nodejs 8+

**Comment by derwish-pro** [comment]
Do not change this option, it is not implemented yet.
